// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestMap.Persistence.Ef;

#nullable disable

namespace TestMap.Migrations
{
    [DbContext(typeof(TestMapDbContext))]
    partial class TestMapDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.CSharpProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BuildMetadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("build_metadata");

                    b.Property<string>("BuildTargets")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("build_targets");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("DefaultBuildTarget")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_build_target");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<int>("SolutionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("solution_id");

                    b.HasKey("Id");

                    b.ToTable("csharp_projects", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.CSharpSolutionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.HasKey("Id");

                    b.ToTable("csharp_solutions", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.CodeMetricEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ClassCoupling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("class_coupling");

                    b.Property<int>("CyclomaticComplexity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cyclomatic_complexity");

                    b.Property<int>("DepthOfInheritance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depth_of_inheritance");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<int>("ExecutableLinesOfCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("executable_lines_of_code");

                    b.Property<int>("MaintainabilityIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("maintainability_index");

                    b.Property<int>("SourceLinesOfCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_lines_of_code");

                    b.HasKey("Id");

                    b.ToTable("code_metrics", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.FileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CSharpProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("csharp_project_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("UsingStatements")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("using_statements");

                    b.HasKey("Id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.InvocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("FullString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_string");

                    b.Property<int?>("InvokedMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("invoked_member_id");

                    b.Property<bool>("IsAssertion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_assertion");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.HasKey("Id");

                    b.ToTable("invocations", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.MemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("DocString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("doc_string");

                    b.Property<string>("FullString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_string");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_generated");

                    b.Property<bool>("IsTestMember")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_test_member");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ObjectEntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("object_id");

                    b.Property<string>("TestCategories")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_categories");

                    b.Property<string>("TestIntent")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_intent");

                    b.Property<double?>("TestMetadataConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("test_metadata_confidence");

                    b.Property<string>("TestMetadataPromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_metadata_prompt_version");

                    b.Property<string>("TestMetadataSource")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_metadata_source");

                    b.HasKey("Id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.MemberRelationshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RelationshipType");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SourceId");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TargetId");

                    b.HasKey("Id");

                    b.ToTable("MemberRelationships", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.ObjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("attributes");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("DocString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("doc_string");

                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_id");

                    b.Property<string>("FullString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_string");

                    b.Property<bool>("IsTestObject")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_test_object");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("namespace");

                    b.Property<string>("TestFramework")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_framework");

                    b.HasKey("Id");

                    b.ToTable("objects", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.ObjectRelationshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RelationshipType");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SourceId");

                    b.Property<int>("TargetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TargetId");

                    b.HasKey("Id");

                    b.ToTable("ObjectRelationships", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Coverage.CoverageGapEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConditionCoverage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("condition_coverage");

                    b.Property<int>("CoverageReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage_report_id");

                    b.Property<string>("GapKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("gap_kind");

                    b.Property<int>("Hits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hits");

                    b.Property<bool>("IsBranch")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_branch");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line_number");

                    b.Property<string>("MemberContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("member_content_hash");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageReportId", "MemberId", "LineNumber", "GapKind")
                        .IsUnique();

                    b.ToTable("coverage_gaps", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Coverage.CoverageReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("BranchRate")
                        .HasColumnType("REAL")
                        .HasColumnName("branch_rate");

                    b.Property<int>("BranchesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_covered");

                    b.Property<int>("BranchesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_valid");

                    b.Property<double>("Complexity")
                        .HasColumnType("REAL")
                        .HasColumnName("complexity");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("LineRate")
                        .HasColumnType("REAL")
                        .HasColumnName("line_rate");

                    b.Property<int>("LinesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_covered");

                    b.Property<int>("LinesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_valid");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timestamp");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("coverage_reports", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Coverage.MemberCoverageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("BranchRate")
                        .HasColumnType("REAL")
                        .HasColumnName("branch_rate");

                    b.Property<int>("BranchesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_covered");

                    b.Property<int>("BranchesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_valid");

                    b.Property<double>("Complexity")
                        .HasColumnType("REAL")
                        .HasColumnName("complexity");

                    b.Property<int>("CoverageReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage_report_id");

                    b.Property<double>("LineRate")
                        .HasColumnType("REAL")
                        .HasColumnName("line_rate");

                    b.Property<int>("LinesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_covered");

                    b.Property<int>("LinesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_valid");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.HasKey("Id");

                    b.ToTable("member_coverages", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Coverage.ObjectCoverageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("BranchRate")
                        .HasColumnType("REAL")
                        .HasColumnName("branch_rate");

                    b.Property<int>("BranchesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_covered");

                    b.Property<int>("BranchesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("branches_valid");

                    b.Property<double>("Complexity")
                        .HasColumnType("REAL")
                        .HasColumnName("complexity");

                    b.Property<int>("CoverageReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage_report_id");

                    b.Property<double>("LineRate")
                        .HasColumnType("REAL")
                        .HasColumnName("line_rate");

                    b.Property<int>("LinesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_covered");

                    b.Property<int>("LinesValid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lines_valid");

                    b.Property<int>("ObjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("object_id");

                    b.HasKey("Id");

                    b.ToTable("object_coverages", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.CandidateMethodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("ExistingTestMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("existing_test_member_id");

                    b.Property<string>("ExistingTestMethodName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("existing_test_method_name");

                    b.Property<double?>("ExpectedMetricDelta")
                        .HasColumnType("REAL")
                        .HasColumnName("expected_metric_delta");

                    b.Property<int>("ExperimentRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("experiment_run_id");

                    b.Property<double>("InitialCoverage")
                        .HasColumnType("REAL")
                        .HasColumnName("initial_coverage");

                    b.Property<int>("InitialCoveredLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_covered_lines");

                    b.Property<int>("InitialTotalLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("initial_total_lines");

                    b.Property<double?>("MetricConfidence")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_confidence");

                    b.Property<double?>("MetricDrivenScore")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_driven_score");

                    b.Property<double?>("MetricEstimatedCost")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_estimated_cost");

                    b.Property<double?>("MetricFeasibility")
                        .HasColumnType("REAL")
                        .HasColumnName("metric_feasibility");

                    b.Property<string>("MetricGuardrailStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_guardrail_status");

                    b.Property<string>("MetricSelectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metric_selection_reason");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("recommended_action");

                    b.Property<DateTime>("SelectionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("selection_time");

                    b.Property<int>("SourceMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_member_id");

                    b.Property<string>("SourceMethodName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_method_name");

                    b.Property<string>("SourceMethodSignature")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_method_signature");

                    b.Property<string>("TestImprovementReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_improvement_reason");

                    b.Property<double?>("TestImprovementScore")
                        .HasColumnType("REAL")
                        .HasColumnName("test_improvement_score");

                    b.Property<string>("TestState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("test_state");

                    b.Property<string>("TestStateReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_state_reason");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentRunId");

                    b.ToTable("candidate_methods", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.ExperimentRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CandidateLimit")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_limit");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("configuration");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("experiment_runs", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_number");

                    b.Property<int>("CandidateMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_method_id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FailureCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_category");

                    b.Property<string>("FailureKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_kind");

                    b.Property<string>("FailureStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_stage");

                    b.Property<bool>("IsRepairAttempt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_repair_attempt");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_name");

                    b.Property<int?>("ParentAttemptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_attempt_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider_name");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("strategy");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_tokens_used");

                    b.HasKey("Id");

                    b.HasIndex("CandidateMethodId");

                    b.HasIndex("ParentAttemptId");

                    b.ToTable("generation_attempts", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.GenerationStepEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("end_time");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("GenerationAttemptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation_attempt_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("prompt");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_time");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tokens_used");

                    b.Property<string>("ValidationResult")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("validation_result");

                    b.HasKey("Id");

                    b.HasIndex("GenerationAttemptId");

                    b.ToTable("generation_steps", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.TestExecutionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssertionErrors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("assertion_errors");

                    b.Property<double?>("BaselineMutationScore")
                        .HasColumnType("REAL")
                        .HasColumnName("baseline_mutation_score");

                    b.Property<string>("CompilationErrors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compilation_errors");

                    b.Property<bool>("CompilationSucceeded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("compilation_succeeded");

                    b.Property<double>("CoverageDelta")
                        .HasColumnType("REAL")
                        .HasColumnName("coverage_delta");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_time");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("execution_time_ms");

                    b.Property<double>("FinalCoverage")
                        .HasColumnType("REAL")
                        .HasColumnName("final_coverage");

                    b.Property<int>("FinalCoveredLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("final_covered_lines");

                    b.Property<int>("FinalTotalLines")
                        .HasColumnType("INTEGER")
                        .HasColumnName("final_total_lines");

                    b.Property<string>("GeneratedTestCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_test_code");

                    b.Property<string>("GeneratedTestMethodName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("generated_test_method_name");

                    b.Property<int>("GenerationAttemptId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("generation_attempt_id");

                    b.Property<double?>("MutationScoreAfter")
                        .HasColumnType("REAL")
                        .HasColumnName("mutation_score_after");

                    b.Property<double?>("MutationScoreDelta")
                        .HasColumnType("REAL")
                        .HasColumnName("mutation_score_delta");

                    b.Property<int>("NewLinesCovered")
                        .HasColumnType("INTEGER")
                        .HasColumnName("new_lines_covered");

                    b.Property<string>("RuntimeErrors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runtime_errors");

                    b.Property<string>("StructuredErrors")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("structured_errors");

                    b.Property<string>("TestClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("test_classification");

                    b.Property<bool>("TestPassed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_passed");

                    b.HasKey("Id");

                    b.HasIndex("GenerationAttemptId")
                        .IsUnique();

                    b.ToTable("test_executions", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.FlakyTestDetection.FlakyTestRerunResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempt_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int>("TestExecutionResultId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_execution_result_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("TestExecutionResultId");

                    b.ToTable("flaky_test_rerun_results", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.FlakyTestDetection.FlakyTestScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence");

                    b.Property<string>("FactorScores")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("factor_scores");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<double>("FlakinessScore")
                        .HasColumnType("REAL")
                        .HasColumnName("flakiness_score");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<int?>("TestMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_member_id");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_name");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weights");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("TestMemberId");

                    b.HasIndex("TestName", "FilePath");

                    b.ToTable("flaky_test_scores", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.FlakyTestDetection.TestExecutionResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_stack_trace");

                    b.Property<string>("ExecutionContext")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_context");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_path");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("SolutionPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("solution_path");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_framework");

                    b.Property<int?>("TestMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_member_id");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_name");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("TestMemberId");

                    b.HasIndex("TestName", "FilePath");

                    b.ToTable("test_execution_results", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.MutationTesting.MutantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("CoveredBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("covered_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_static");

                    b.Property<string>("KilledBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("killed_by");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<int?>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<int>("MutationTestingReportId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mutation_testing_report_id");

                    b.Property<string>("MutatorName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mutator_name");

                    b.Property<string>("Replacement")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("replacement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status_reason");

                    b.Property<string>("StrykerMutantId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stryker_mutant_id");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("mutants", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.MutationTesting.MutantSurvivedTestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("location");

                    b.Property<int>("MutantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mutant_id");

                    b.Property<string>("StrykerTestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stryker_test_id");

                    b.Property<string>("TestFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_file_path");

                    b.Property<int?>("TestMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_member_id");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_name");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.ToTable("mutant_survived_tests", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.MutationTesting.MutationTestingReportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Files")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("files");

                    b.Property<double>("MutationScore")
                        .HasColumnType("REAL")
                        .HasColumnName("mutation_score");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectRoot")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project_root");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schema_version");

                    b.Property<string>("TestFiles")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_files");

                    b.Property<string>("Thresholds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("thresholds");

                    b.HasKey("Id");

                    b.ToTable("mutation_testing_reports", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("branch");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabasePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("database_path");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("directory_path");

                    b.Property<string>("LastAnalyzedCommit")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_analyzed_commit");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("repo_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("web_url");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.RiskScoring.CandidateMethodRiskScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("CandidateMethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("candidate_method_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FactorScores")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("factor_scores");

                    b.Property<int>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<double>("RiskScore")
                        .HasColumnType("REAL")
                        .HasColumnName("risk_score");

                    b.Property<string>("SelectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("selection_reason");

                    b.Property<string>("Weights")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("weights");

                    b.HasKey("Id");

                    b.HasIndex("CandidateMethodId");

                    b.HasIndex("MemberId");

                    b.ToTable("candidate_method_risk_scores", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Testing.TestResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("TEXT")
                        .HasColumnName("duration");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<int>("MethodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("method_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("RunDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_date");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_name");

                    b.Property<int>("TestRunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("test_run_id");

                    b.HasKey("Id");

                    b.ToTable("test_results", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Testing.TestRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Coverage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("coverage");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureAnalysis")
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_analysis");

                    b.Property<string>("LogPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("log_path");

                    b.Property<double?>("MutationScore")
                        .HasColumnType("REAL")
                        .HasColumnName("mutation_score");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("RunDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_date");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.ToTable("test_runs", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Testing.TestSmellEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AnalyzedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("analyzed_at_utc");

                    b.Property<int?>("Column")
                        .HasColumnType("INTEGER")
                        .HasColumnName("column");

                    b.Property<string>("ContainingTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("containing_type_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<int?>("Line")
                        .HasColumnType("INTEGER")
                        .HasColumnName("line");

                    b.Property<int?>("MemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("member_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("object_id");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("project_id");

                    b.Property<string>("SmellId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("smell_id");

                    b.Property<string>("SmellName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("smell_name");

                    b.Property<string>("TestMethodName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_method_name");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ObjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SmellId");

                    b.HasIndex("ProjectId", "MemberId", "SmellId", "FilePath", "Line", "Column");

                    b.ToTable("test_smells", (string)null);
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.MemberEntity", b =>
                {
                    b.OwnsOne("TestMap.Models.Code.Location", "Location", b1 =>
                        {
                            b1.Property<int>("MemberEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BodyEndPosition")
                                .HasColumnType("INTEGER")
                                .HasColumnName("body_end_position");

                            b1.Property<int>("BodyStartPosition")
                                .HasColumnType("INTEGER")
                                .HasColumnName("body_start_position");

                            b1.Property<int>("EndLineNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_line_number");

                            b1.Property<int>("StartLineNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_line_number");

                            b1.HasKey("MemberEntityId");

                            b1.ToTable("members");

                            b1.WithOwner()
                                .HasForeignKey("MemberEntityId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Code.ObjectEntity", b =>
                {
                    b.OwnsOne("TestMap.Models.Code.Location", "Location", b1 =>
                        {
                            b1.Property<int>("ObjectEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BodyEndPosition")
                                .HasColumnType("INTEGER")
                                .HasColumnName("body_end_position");

                            b1.Property<int>("BodyStartPosition")
                                .HasColumnType("INTEGER")
                                .HasColumnName("body_start_position");

                            b1.Property<int>("EndLineNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("end_line_number");

                            b1.Property<int>("StartLineNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("start_line_number");

                            b1.HasKey("ObjectEntityId");

                            b1.ToTable("objects");

                            b1.WithOwner()
                                .HasForeignKey("ObjectEntityId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.CandidateMethodEntity", b =>
                {
                    b.HasOne("TestMap.Persistence.Ef.Entities.Experiment.ExperimentRunEntity", "ExperimentRun")
                        .WithMany("CandidateMethods")
                        .HasForeignKey("ExperimentRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperimentRun");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", b =>
                {
                    b.HasOne("TestMap.Persistence.Ef.Entities.Experiment.CandidateMethodEntity", "CandidateMethod")
                        .WithMany("GenerationAttempts")
                        .HasForeignKey("CandidateMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", "ParentAttempt")
                        .WithMany()
                        .HasForeignKey("ParentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CandidateMethod");

                    b.Navigation("ParentAttempt");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.GenerationStepEntity", b =>
                {
                    b.HasOne("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", "GenerationAttempt")
                        .WithMany("GenerationSteps")
                        .HasForeignKey("GenerationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationAttempt");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.TestExecutionEntity", b =>
                {
                    b.HasOne("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", "GenerationAttempt")
                        .WithOne("TestExecution")
                        .HasForeignKey("TestMap.Persistence.Ef.Entities.Experiment.TestExecutionEntity", "GenerationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationAttempt");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.CandidateMethodEntity", b =>
                {
                    b.Navigation("GenerationAttempts");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.ExperimentRunEntity", b =>
                {
                    b.Navigation("CandidateMethods");
                });

            modelBuilder.Entity("TestMap.Persistence.Ef.Entities.Experiment.GenerationAttemptEntity", b =>
                {
                    b.Navigation("GenerationSteps");

                    b.Navigation("TestExecution");
                });
#pragma warning restore 612, 618
        }
    }
}
